# Generated by Django 6.0.1 on 2026-01-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zomatoDB',
            fields=[
                ('Name', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_no', models.IntegerField()),
                ('OTP', models.IntegerField(primary_key=True, serialize=False)),
                ('Time', models.TimeField()),
                ('Ratings', models.FloatField()),
                ('Amount', models.FloatField()),
            ],
        ),
    ]
